### ISSUE TITLE
ESLint: 8.8.0 is not happy 

### ISSUE THREAD

**Issue by flexbox** [wcandillon/eslint-config-react-native-wcandillon#241]
Hey! 
Thanks for this I am using it all the time on my projects 🚀 

Here is my issue

As a developer
I can setup the last eslint version
So that I am up-to-date

---

If I run the instructions 

```console
yarn add eslint --dev
```
will install
```
info All dependencies
├─ @eslint/eslintrc@1.0.5
...
├─ eslint@8.8.0
```

**Problem**
```console
yarn lint
```

```
yarn run v1.22.17
$ eslint --ignore-path .gitignore --ext .js,.ts,.tsx .

Oops! Something went wrong! :(

ESLint: 8.8.0

TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » eslint-config-react-native-wcandillon': Class extends value undefined is not a constructor or null
Referenced from: /Users/cerebra/workspace/rn/react-native-bootcamp/hackathon/react-native-heroes/node_modules/eslint-config-react-native-wcandillon/index.js
    at Object.<anonymous> (/Users/cerebra/workspace/rn/react-native-bootcamp/hackathon/react-native-heroes/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (/Users/cerebra/workspace/rn/react-native-bootcamp/hackathon/react-native-heroes/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/cerebra/workspace/rn/react-native-bootcamp/hackathon/react-native-heroes/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/cerebra/workspace/rn/react-native-bootcamp/hackathon/react-native-heroes/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (/Users/cerebra/workspace/rn/react-native-bootcamp/hackathon/react-native-heroes/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Solution** 
Downgrade the version will fix the problem 
```console
yarn add --dev eslint@7.32.0 
```

Or I think we will to update dependencies

**Comment by wcandillon** [comment]
Reopening since installing the latest version doesn't seem to use the added resolutions

**Comment by wcandillon** [comment]
this is fixed finally :)

**Comment by flexbox** [comment]
Confirmed! 

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/360936/185353371-aa0db4cd-ea44-4c9d-a544-36e159afcc68.png">

<img width="497" alt="image" src="https://user-images.githubusercontent.com/360936/185353398-7d618f11-49b4-46f9-a763-65759d3b8a10.png">

Thank you for you work 🙌

**Comment by wcandillon** [comment]
no no no no David: Thank You 😉
